### ISSUE TITLE
二级菜单不显示

### ISSUE THREAD

**Issue by Fyp-space** [HowieHz/halo-theme-higan-hz#57]
麻烦问一下，已配置二级菜单但点击分类主菜单不展示子菜单。是什么原因嘞？
![image](https://github.com/HowieHz/halo-theme-higan-hz/assets/130546218/4896c88f-7711-45c3-ac26-7210cd195455)

**Comment by HowieHz** [comment]
这个是主题风格

**Comment by HowieHz** [comment]
https://github.com/guqing/halo-theme-higan/issues/116
上游提出了相同的 issue，现在在考虑样式

**Comment by HowieHz** [comment]
我认为当前的主题的风格和样式不适合添加二级菜单，在美观度上会打折扣。
如果有人提出合适的样式我会添加。
