### ISSUE TITLE
halo 设置 页脚 未填充到最底部

### ISSUE THREAD

**Issue by ouostar** [HowieHz/halo-theme-higan-hz#60]
footer不在最底部

**Comment by HowieHz** [comment]
不好意思，邮箱里漏了这个没看到。
能截图仔细说明下你的问题吗？

**Comment by HowieHz** [comment]
本分支在“首页样式”设置项中有提供可能是你提到的相关配置选项
```
  允许关闭页面底部主题信息
  允许关闭页面底部版权信息
  允许关闭页面底部菜单
```

**Comment by HowieHz** [comment]
https://github.com/HowieHz/halo-theme-higan-hz/releases/tag/v1.6.0
1.6.0 新增配置项（总体样式-添加内容到页脚最底部）允许用户添加内容到页脚最底部 解决了此问题

**Comment by ouostar** [comment]
抱歉 没看见
![Image_1723882365351](https://github.com/user-attachments/assets/7c4b99cb-9e54-4ee4-9ab6-79504b6146bf)

**Comment by ouostar** [comment]
![Image_1723882705784](https://github.com/user-attachments/assets/0e69f34d-301d-4b08-8f79-e4a8292cbc7d)
抱歉 没看见
竖屏状态下 没有足够的内容 页脚不在屏幕的最底部

**Comment by HowieHz** [comment]
已修复 https://github.com/HowieHz/halo-theme-higan-hz/releases/tag/v1.6.1
