### ISSUE TITLE
文字区过少时改内容宽度为 70% 首页未居中

### ISSUE THREAD

**Issue by jalr4ever** [HowieHz/halo-theme-higan-hz#67]
内容区域最大宽度 48rem：
<img width="1518" alt="iShot_2024-10-12_11 20 48" src="https://github.com/user-attachments/assets/b095f6fb-4010-480c-8dea-b4319dfa15e7">

内容区域最大宽度 70% ：
<img width="1541" alt="iShot_2024-10-12_11 21 11" src="https://github.com/user-attachments/assets/baaf66ee-c072-48c5-a2e8-250cce5de9dc">

如图改了宽度后，首页变得居左了，首页能否保留 48em 那种居中的效果呢？

**Comment by HowieHz** [comment]
已读，正在检查此问题

**Comment by HowieHz** [comment]
flex 框一直是居中的，设置为 70% 的时候 flex 框变大了，内部的文字依然从左开始，在文字比较少的页面上就体现的是整体偏左
![image](https://github.com/user-attachments/assets/9638fabf-315c-4dd4-b857-4cb4c8e056d3)
![image](https://github.com/user-attachments/assets/6cd00d39-b7a9-4746-b7cb-767c9aa65266)

调成 78rem 也有类似的现象
![image](https://github.com/user-attachments/assets/f9b2e6ef-b33e-41ac-bf47-895fe322e4fb)

**Comment by HowieHz** [comment]
我猜测，理想的样式可能是

设置一个宽度最小值（如 48rem）和一个宽度最大值（如 70%）
按照最长的文字设置这个框的宽度，把这个框撑大
如果一行文字超过宽度最大值，就给这行文字换行

**Comment by jalr4ever** [comment]
@HowieHz 这个方案不错，如果 70% 一开始会感觉很空，会居左显示

**Comment by HowieHz** [comment]
关联上游 issue https://github.com/guqing/halo-theme-higan/issues/118

**Comment by HowieHz** [comment]
已发布新版本
https://github.com/HowieHz/halo-theme-higan-hz/releases/tag/v1.9.0

## 简述版

现在要解决这个看起来不居中的问题，你只需要去开启“自定义内容区域最小宽度”和“自定义内容区域宽度属性”即可。

## 完整描述版

如果你要用上游原主题的宽度设置，那就关闭“自定义内容区域最大宽度”，开启“自定义内容区域最小宽度”和“自定义内容区域宽度属性”。

如果你要设定最大宽度为 70%，那就开启“自定义内容区域最大宽度”设定为 70%，并开启“自定义内容区域最小宽度”和“自定义内容区域宽度属性”。
