### ISSUE TITLE
Enhance - 主页添加夜间模式和日间模式手动切换按钮

### ISSUE THREAD

**Issue by jalr4ever** [HowieHz/halo-theme-higan-hz#81]
# 期望

类似：https://lilianweng.github.io/ 中的名称旁边，能有一个可以切换的按钮，日间模式是小月亮，夜间模式是小太阳，一点就能切换，最好显眼一点

**Comment by HowieHz** [comment]
#13 好的，我会尽快添加

**Comment by HowieHz** [comment]
32d96282681612d9afc7571baec25044ae08eefa 等待发版
