### ISSUE TITLE
为仓库提供 CONTRIBUTING Doc

### ISSUE THREAD

**Issue by jalr4ever** [HowieHz/halo-theme-higan-hz#99]
目的是为了让更多人参与到仓库的建设，参考：

-  [CONTRIBUTING](https://github.com/hitsz-ids/synthetic-data-generator/blob/main/CONTRIBUTING.md) 
- [CONTRIBUTING.md](https://github.com/All-Hands-AI/OpenHands/blob/main/CONTRIBUTING.md)
- [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md)

**Comment by HowieHz** [comment]
简单写就好，把项目开发准备这一段从 readme 摘出来
